#!/bin/bash



ln -sf $PWD/bashrc ~/.bashrc
ls -l ~/.bashrc

ln -sf $PWD/vimrc $HOME/.vimrc
ls -l $HOME/.vimrc


ln -sf $PWD/vimrc /root/.vimrc
ls -l /root/.vimrc

ln -sf $PWD/scripts/tmux.conf $HOME/.tmux.conf
ls -l $HOME/.tmux.conf
