#!/bin/bash


ln -sf $PWD/bash_aliases ~/.bash_aliases
ls -l ~/.bash_aliases

ln -sf $PWD/bashrc ~/.bashrc
ls -l ~/.bashrc

ln -sf $PWD/vimrc $HOME/.vimrc
ls -l $HOME/.vimrc

ln -sf $PWD/tmux.conf $HOME/.tmux.conf
ls -l $HOME/.tmux.conf
