#!/bin/bash



ln -sf $PWD/bashrc ~/.bashrc
ls -l ~/.bashrc

ln -sf $PWD/vimrc $HOME/.vimrc
ls -l $HOME/.vimrc

ln -sf $PWD/tmux.conf $HOME/.tmux.conf
ls -l $HOME/.tmux.conf

ln -sf $PWD/bash_profile $HOME/.bash_profile
ls -l $HOME/.bash_profile

ln -sf $PWD/gdbinit ~/.gdbinit
ls -l ~/.gdbinit
