#!/bin/bash

cd_to_script () {
  cd $modified_path

}

if [[ -z $(which $1) ]]; then
  echo "not a script on the path"
  exit 1
else
  script_path=$(which $1)
  modified_path=${script_path%%\/\/*}
i 
  cd_to_script
fi

