#!/bin/bash

clear

while true; do
  for n in {1..4}
  do
    if [ $n -eq 1 ]
       then 
       char=n
    elif [ $n -eq 2 ]
       then
       char=y
    elif [ $n -eq 3 ]
       then
       char=a
    elif [ $n -eq 4 ]
       then
       char=n
    fi
    echo -en "$(rndcolor)$char"
    done
done

