#!/bin/bash
declare -i k=9
declare -i i=9
declare -i n=0
while true
do
  sleep 0.1
  echo -e ${reset}
  n=$(($i%$k))
  i=$(($i+1))
  if [ $n -eq 0 ]
  then
    echo -e "${bakblk}                                                                         "                                                        
  elif [ $n -eq 1 ]
  then
    echo -e "${bakred}                                                                         "                                                        
  elif [ $n -eq 2 ]
  then
    echo -e "${bakgrn}                                                                         "                                                        
  elif [ $n -eq 3 ]
  then
    echo -e "${bakylw}                                                                         "                                                        
  elif [ $n -eq 4 ]
  then
    echo -e "${bakblu}                                                                         "                                                        
  elif [ $n -eq 5 ]
  then
    echo -e "${bakpur}                                                                         "                                                        
  elif [ $n -eq 6 ]
  then
    echo -e "${bakcyn}                                                                         "                                                        
  elif [ $n -eq 7 ]
  then
    echo -e "${bakwht}                                                                         "                                                        
  else
    echo -e "${undred} fuck you"
  fi 
done  
  
  




