#!/bin/bash

# credit to arthurattwell on github whose script I based this of off 

filename=$1

if [ -z $filename ]; then
  echo "usage: seperator (Mardown file with YAML frontmatter)"
  exit 1
else
  echo 'splitting' $filename '...'
fi

## replaces the upper '---' in each YAML frontmatter to '---csplitline' so csplit can use it

perl -i -0pe 's/(^---$)(.+?)(^---$)/---csplitline$2---/gms' $filename

## count the number of splits
num_of_splits=$(grep -c "^\-\-\-csplitline$" "$filename")
echo "splitting into $num_of_splits seperate files..."

num_of_splits=$(( num_of_splits - 1 ))

## split the file up into multiple files composed of the text between the YAML frontmatter
## files are named xx{0..(num_of_splits)}
csplit -ks $filename '/---csplitline/' {$num_of_splits}

## re insert the '---' into the frontmatter of the original file
perl -i -pe 's/---csplitline/---/' $filename

rm xx00

for file in xx*
do
  perl -i -pe 's/---csplitline/---/' $file
  title_line=$(grep "title:" $file)
  
  dirname=${title_line##* }
  if [ ! -d "./$dirname"  ]; then
    mkdir $dirname
  fi
  echo here is $dirname  
  command mv $file ./$dirname/README.md
done

