#!/bin/bash

# credit to arthurattwell on github whose main structure I used

filename=$1

if [ -z $filename ]; then
  echo "usage: seperator (file.md)"
  exit 1
else
  echo 'splitting' $filename '...'
fi

perl -i -0pe 's/(^---$)(.+?)(^---$)/---csplitline$2---/gms' $filename

num_of_splits=$(grep -c "^\-\-\-csplitline$" "$filename")
echo "splitting into $num_of_splits seperate files..."

num_of_splits=$(( num_of_splits - 1 ))


csplit -ks $filename '/---csplitline/' {$num_of_splits}

perl -i -pe 's/---csplitline/---/' $filename


for file in xx*
do
  perl -i -pe 's/---csplitline/---/' $file
  title_line=$(grep "title:" $file)
  
  dirname=${title_line##* }
  if [ ! -d "./$dirname"  ]; then
    mkdir $dirname
  fi
  echo here is $dirname  
  command mv $file ./$dirname/README.md
done

