#!/bin/bash

#do s=$(dirname $s);b="../${b}"; done; echo ${b}${d#$s/}
#s=$(cd ${1%%/};pwd); d=$(cd $2;pwd); b=; while [ "${d#$s/}" == "${d}" ]
pwd=$PWD
notes
wiki_name=$(find  -name "$1")
path_name="~/repos/gitlab.com/snapplesacue/notes/${wiki_name#*\/}/README.md"
final_path=${realpath --realtive-to="$pwd" " $path_name"}
echo -n "[$2]($final_path)"


